### ISSUE TITLE
ssl.wrap_socket error

### ISSUE THREAD

**Issue by tribunskiysm** [jnthas/clock-club#6]
Error when starting server on Python 3.11.4

PS C:\clock-club-main\local> python local-server.py
Creating SSL Server on local IP 192.168.88.30 and port 4443
Please, put the same IP address in the card called '[Canvas] Server Address' in the settings page of Clockwise
Traceback (most recent call last):
  File "C:\clock-club-main\local\local-server.py", line 29, in <module>
    createServer()
  File "C:\clock-club-main\local\local-server.py", line 21, in createServer
    httpd.socket = ssl.wrap_socket (httpd.socket,
                   ^^^^^^^^^^^^^^^

To solve the problem, we unpack the files into \local

[local.zip](https://github.com/jnthas/clock-club/files/13801324/local.zip)

**Comment by jnthas** [comment]
Hi @tribunskiysm. Thank you. I'm going to update the script if you don't want to open a PR
